### ISSUE TITLE
Server Error - Function getBody() on null

### ISSUE THREAD

**Issue by DYNSOL** [benface/grav-plugin-freshdesk#1]
Hi,

I'm new to Grav so apologies for my lack of technical knowledge of it's inner workings.

I've recently installed the FreshDesk plugin. I've added it to a modular page using the built in Form.md (that comes with Antimatter).

However, once i've added the shortcode and try to submit a ticket, it fails with:

Server Error
0 - Call to member function getBody() on Null.

It also appears to break my other contact form with this error:

Server Error
0 - Freshdesk "subject" is required.

Could you please help resolve this issue?

Thanks in advance.

**Comment by benface** [comment]
Hey @DYNSOL, I can't reproduce this. Can you please share your code? (the .md file of the page containing the form, as well as the template you're using) Thanks!

**Comment by benface** [comment]
@DYNSOL Gentle bump :)

**Comment by benface** [comment]
Closing for now, feel free to reopen with repro steps.
